In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
df = pd.read_csv('/content/diabetes_prediction_dataset.csv')

In [17]:
# Display the first few rows of the dataset
print(df.head())

   gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0  


In [18]:
# Check for missing values
print(df.isnull().sum())

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64


In [19]:
df = df.dropna()

In [22]:
# Select features (X) and target (y)
X = df[['blood_glucose_level', 'bmi']]
y = df['diabetes']


In [23]:
print(X.head())
print(y.head())

   blood_glucose_level    bmi
0                  140  25.19
1                   80  27.32
2                  158  27.32
3                  155  23.45
4                  155  20.14
0    0
1    0
2    0
3    0
4    0
Name: diabetes, dtype: int64


In [24]:
 # Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [25]:
print(X_train.shape, X_test.shape)

(70000, 2) (30000, 2)


In [26]:
# Create the Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [27]:
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [28]:
# Make predictions on the test set
y_pred = rf.predict(X_test)


In [29]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [30]:
# Print the evaluation results
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9297
Confusion Matrix:
[[26795   658]
 [ 1451  1096]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.96     27453
           1       0.62      0.43      0.51      2547

    accuracy                           0.93     30000
   macro avg       0.79      0.70      0.74     30000
weighted avg       0.92      0.93      0.92     30000



In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
df = pd.read_csv('/content/diabetes_prediction_dataset.csv')

In [33]:
print(df.head())

   gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0  


In [34]:
# Check for missing values
print(df.isnull().sum())

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64


In [36]:
df = df.dropna() #drop missing rows

In [38]:
# Select features (X) and target (y)
X = df[['blood_glucose_level', 'bmi']]
y = df['diabetes']


In [39]:
print(X.head())
print(y.head())

   blood_glucose_level    bmi
0                  140  25.19
1                   80  27.32
2                  158  27.32
3                  155  23.45
4                  155  20.14
0    0
1    0
2    0
3    0
4    0
Name: diabetes, dtype: int64


In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [41]:
print(X_train.shape, X_test.shape)

(70000, 2) (30000, 2)


In [43]:
# Create the knn classifeir
knn = KNeighborsClassifier(n_neighbors=5)

In [44]:
# train the model
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [45]:
y_pred = knn.predict(X_test)

In [46]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [47]:
# Print the evaluation results
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9421333333333334
Confusion Matrix:
[[27261   192]
 [ 1544  1003]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97     27453
           1       0.84      0.39      0.54      2547

    accuracy                           0.94     30000
   macro avg       0.89      0.69      0.75     30000
weighted avg       0.94      0.94      0.93     30000



In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [68]:
df = pd.read_csv('/content/diabetes_prediction_dataset.csv')


In [69]:
df = df.dropna()

In [70]:
# Select features (X) and target (y)
X = df[['blood_glucose_level', 'bmi',]]
y = df['diabetes']

In [71]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [72]:
lr = LinearRegression()

In [73]:
# Train the model
lr.fit(X_train, y_train)

LinearRegression()

In [74]:
# Make predictions on the test set
y_pred_continuous = lr.predict(X_test)

In [75]:
# Convert continuous predictions to binary predictions
y_pred = np.where(y_pred_continuous >= 0.5, 1, 0)

In [76]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


In [77]:
# Print the evaluation results
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9264
Confusion Matrix:
[[27446     7]
 [ 2201   346]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.96     27453
           1       0.98      0.14      0.24      2547

    accuracy                           0.93     30000
   macro avg       0.95      0.57      0.60     30000
weighted avg       0.93      0.93      0.90     30000



In [78]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [79]:
df = pd.read_csv('/content/diabetes_prediction_dataset.csv')

In [80]:
df = df.dropna()

In [81]:
# Select features (X) and target (y)
X = df[['blood_glucose_level', 'bmi']]
y = df['diabetes']


In [82]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [87]:
# Create the Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=42)

In [88]:
# Train the model
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [89]:
# Make predictions on the test set
y_pred = dt.predict(X_test)

In [90]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [91]:
# Print the results
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9311333333333334
Confusion Matrix:
[[26839   614]
 [ 1452  1095]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.96     27453
           1       0.64      0.43      0.51      2547

    accuracy                           0.93     30000
   macro avg       0.79      0.70      0.74     30000
weighted avg       0.92      0.93      0.92     30000



In [ ]:
# 94% knn accuracy is highest

In [92]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [93]:
df = pd.read_csv('/content/diabetes_prediction_dataset.csv')

In [94]:
df = df.dropna()

In [95]:
# Select features (X) and target (y)
X = df[['blood_glucose_level', 'bmi']]
y = df['diabetes']

In [96]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [97]:
# Create the AdaBoost Classifier
adb = AdaBoostClassifier(n_estimators=50, random_state=42)


In [98]:
# Train the model
adb.fit(X_train, y_train)

AdaBoostClassifier(random_state=42)

In [99]:
# Make predictions on the test set
y_pred = adb.predict(X_test)

In [103]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [104]:
# Print the evaluation results
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.9474333333333333
Confusion Matrix:
[[27453     0]
 [ 1577   970]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97     27453
           1       1.00      0.38      0.55      2547

    accuracy                           0.95     30000
   macro avg       0.97      0.69      0.76     30000
weighted avg       0.95      0.95      0.94     30000

